### ISSUE TITLE
UI crashes when home screen is set to feed.

### ISSUE THREAD

**Issue by johnb-xp** [TeamNewPipe/NewPipe-legacy#1]
When the main screen / home page is set to the subscriptions feed it takes a while to load, and crashes the UI occasionally.
Tapping the feed icon from the subscriptions page loads the feed almost instantly, and without issues.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.15.1
* __OS:__ qnx Android 4.3 - 18

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{37933c90 position=0 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)} android.support.v7.widget.RecyclerView{375cd198 VFED.V.. .F....ID 0,0-800,591 #7f090119 app:id/items_list}, adapter:org.schabi.newpipelegacy.info_list.InfoListAdapter@37591f40, layout:android.support.v7.widget.LinearLayoutManager@375d46d0, context:org.schabi.newpipelegacy.MainActivity@37192970
	at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
	at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
	at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1431)
	at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:4161)
	at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:612)
	at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:240)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3994)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14310)
	at android.view.ViewGroup.layout(ViewGroup.java:4562)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1978)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1732)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1006)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5550)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5121)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```
</p></details>
<hr>

**Comment by moshpirit** [comment]
Is there anyway to solve this issue? since I modified the brightness by gestures on my 4.1.1 android tablet I can't see any videos anymore because, as you said, the UI crashes.
