### ISSUE TITLE
UI crash in Setting > Notifications

### ISSUE THREAD

**Issue by bluezed** [TeamNewPipe/NewPipe-legacy#63]
Going to Settings > Notifications leads to a crash.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.view.InflateException: Binary XML file line #31: Error inflating class (not found)org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:287)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at org.schabi.newpipelegacy.settings.NotificationSettingsFragment.onCreatePreferences(NotificationSettingsFragment.kt:10)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipelegacy.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:24)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:214)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.schabi.newpipe.settings.custom.NotificationActionsPreference
	... 30 more

```
</details>
<hr>

**Comment by ghostrider75de** [comment]
Same here ;)
Selecting the button notifications in the settings will immediately crash the app. Rest is working properly so far.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 4.2.2 - 17
<details><summary><b>Crash log </b></summary><p>

```
android.view.InflateException: Binary XML file line #31: Error inflating class (not found)org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:287)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at org.schabi.newpipelegacy.settings.NotificationSettingsFragment.onCreatePreferences(NotificationSettingsFragment.kt:10)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipelegacy.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:24)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:217)
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:214)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: org/schabi/newpipe/settings/custom/NotificationActionsPreference
	... 32 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.schabi.newpipe.settings.custom.NotificationActionsPreference" on path: /data/app/org.schabi.newpipelegacy-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 32 more

```
</details>
<hr>
