### ISSUE TITLE
The Newpipe-legacy app's UI FAILED..

### ISSUE THREAD

**Issue by TheMaestro00** [TeamNewPipe/NewPipe-legacy#73]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ MX
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
android.view.InflateException: Binary XML file line #31: Error inflating class (not found)org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:287)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at org.schabi.newpipelegacy.settings.NotificationSettingsFragment.onCreatePreferences(NotificationSettingsFragment.kt:10)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipelegacy.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:24)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:869)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:6760)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
Caused by: java.lang.ClassNotFoundException: org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:214)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
	... 26 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.schabi.newpipe.settings.custom.NotificationActionsPreference" on path: DexPathList[[zip file "/data/app/org.schabi.newpipelegacy-ehGe3fGQb3KGeSWywCbRww==/base.apk"],nativeLibraryDirectories=[/data/app/org.schabi.newpipelegacy-ehGe3fGQb3KGeSWywCbRww==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 30 more

```
</details>
<hr>

**Comment by drogga** [comment]
@TheMaestro00 (aka. @TheGrimHack) - Why do you even use this version !?, you have A8 Oreo, use the upstream instead, this one is only for those of us that want to use it on lower/earlier than 4.4 KitKat.

**Comment by TheMaestro00** [comment]
This is the only version that works on my computer handheld device. Or cell phone. If all I'm going to get is complaints I just won't commit errors or whatever to the project and fix it myself. Just trying to be helpful but that doesn't seem like something you guys want.
