### ISSUE TITLE
App crashed on Android 4.0.4 (sh000gun legacy version)

### ISSUE THREAD

**Issue by PCMYONELOVE** [TeamNewPipe/NewPipe-legacy#76]
I'm trying to install the Legacy version by @sh000gun for Android 4.0.4. After launching the application, it crashes. 
Here is the logcat:
`D/MobileDataStateTracker(  452): default: setPolicyDataEnable(enabled=true)
I/Process (14855): Sending signal. PID: 14855 SIG: 9
W/InputMethodManagerService(  452): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4241d098 attribute=null, token = android.os.BinderProxy@41df33d0
I/ActivityManager(  452): Process org.schabi.newpipelegacy (pid 14855) has died.
D/ActivityManager(  452): cleanUpApplicationRecordLocked -- 14855
I/ActivityManager(  452): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.schabi.newpipelegacy/.MainActivity} from pid 623
V/Zygote  (14925): Switching descriptor 32 to /dev/null
V/Zygote  (14925): Switching descriptor 10 to /dev/null
I/ActivityManager(  452): Start proc org.schabi.newpipelegacy for activity org.schabi.newpipelegacy/.MainActivity: pid=14925 uid=10055 gids={50055, 3003, 1028, 1015}
E/dalvikvm(14925): Could not find class 'android.app.NotificationChannel', referenced from method org.schabi.newpipelegacy.App.setUpUpdateNotificationChannel
W/dalvikvm(14925): VFY: unable to resolve new-instance 50 (Landroid/app/NotificationChannel;) in Lorg/schabi/newpipelegacy/App;
D/dalvikvm(14925): VFY: replacing opcode 0x22 at 0x0015
E/dalvikvm(14925): Could not find class 'android.app.NotificationChannel', referenced from method org.schabi.newpipelegacy.App.initNotificationChannel
W/dalvikvm(14925): VFY: unable to resolve new-instance 50 (Landroid/app/NotificationChannel;) in Lorg/schabi/newpipelegacy/App;
D/dalvikvm(14925): VFY: replacing opcode 0x22 at 0x001c
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x0179 at 0x17 in Lorg/schabi/newpipelegacy/App;.setUpUpdateNotificationChannel
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x0179 at 0x1f in Lorg/schabi/newpipelegacy/App;.initNotificationChannel
I/dalvikvm(14925): Could not find method android.content.Context.getNoBackupFilesDir, referenced from method org.acra.file.Directory$6.getFile
W/dalvikvm(14925): VFY: unable to resolve virtual method 508: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
D/dalvikvm(14925): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
I/dalvikvm(14925): Could not find method org.acra.collections.ImmutableSet.iterator, referenced from method org.acra.data.StringFormat$1.toFormattedString
W/dalvikvm(14925): VFY: unable to resolve virtual method 37023: Lorg/acra/collections/ImmutableSet;.iterator ()Ljava/util/Iterator;
D/dalvikvm(14925): VFY: replacing opcode 0x6e at 0x000d
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
I/dalvikvm(14925): Could not find method org.acra.collections.ImmutableSet.iterator, referenced from method org.acra.data.StringFormat$2.toFormattedString
W/dalvikvm(14925): VFY: unable to resolve virtual method 37023: Lorg/acra/collections/ImmutableSet;.iterator ()Ljava/util/Iterator;
D/dalvikvm(14925): VFY: replacing opcode 0x6e at 0x000d
E/rsC++   (  623): RS Message thread exiting.
D/dalvikvm(14925): GC_CONCURRENT freed 223K, 7% free 3409K/3628K, paused 3ms+3ms, total 31ms
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
E/dalvikvm(14925): Could not find class 'org.acra.collections.ImmutableList', referenced from method org.acra.config.CoreConfiguration.<init>
W/dalvikvm(14925): VFY: unable to resolve new-instance 5449 (Lorg/acra/collections/ImmutableList;) in Lorg/acra/config/CoreConfiguration;
D/dalvikvm(14925): VFY: replacing opcode 0x22 at 0x0015
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(14925): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0x1b in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0x2c in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9096 at 0x37 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0x54 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0x71 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0x7c in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0x8d in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9074 at 0xb6 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(14925): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(14925): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(14925): DexOpt: unable to opt direct call 0x9073 at 0xe5 in Lorg/acra/config/CoreConfiguration;.<init>
D/AndroidRuntime(14925): Shutting down VM
W/dalvikvm(14925): threadid=1: thread exiting with uncaught exception (group=0x4193ac08)
E/AndroidRuntime(14925): FATAL EXCEPTION: main
E/AndroidRuntime(14925): Process: org.schabi.newpipelegacy, PID: 14925
E/AndroidRuntime(14925): java.lang.NoClassDefFoundError: org.acra.collections.ImmutableList
E/AndroidRuntime(14925):        at org.acra.config.CoreConfiguration.<init>(CoreConfiguration.java:118)
E/AndroidRuntime(14925):        at org.acra.config.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:835)
E/AndroidRuntime(14925):        at org.schabi.newpipelegacy.App.initACRA(App.java:210)
E/AndroidRuntime(14925):        at org.schabi.newpipelegacy.App.attachBaseContext(App.java:83)
E/AndroidRuntime(14925):        at android.app.Application.attach(Application.java:181)
E/AndroidRuntime(14925):        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
E/AndroidRuntime(14925):        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/AndroidRuntime(14925):        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
E/AndroidRuntime(14925):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
E/AndroidRuntime(14925):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime(14925):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(14925):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14925):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(14925):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(14925):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14925):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14925):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(14925):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime(14925):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  452):   Force finishing activity org.schabi.newpipelegacy/.MainActivity
D/dalvikvm(14925): GC_CONCURRENT freed 391K, 12% free 3525K/3984K, paused 2ms+2ms, total 25ms
W/ActivityManager(  452): Activity pause timeout for ActivityRecord{41f1e080 u0 org.schabi.newpipelegacy/.MainActivity t59 f}
W/GraphicBufferMapper(  623): registerBuffer(0x5f5f8ed8) failed -22 (Invalid argument)
E/GraphicBuffer(  623): unflatten: registerBuffer failed: Invalid argument (-22)
V/RenderScript(  623): 0x5f767418 Launching thread(s), CPUs 2
E/WindowManager(  452): Starting window AppWindowToken{42a06710 token=Token{42217e50 ActivityRecord{41f1e080 u0 org.schabi.newpipelegacy/.MainActivity t59}}} timed out
W/ActivityManager(  452): Activity destroy timeout for ActivityRecord{41f1e080 u0 org.schabi.newpipelegacy/.MainActivity t59 f}
I/Process (14925): Sending signal. PID: 14925 SIG: 9
W/InputMethodManagerService(  452): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42680268 attribute=null, token = android.os.BinderProxy@41df33d0
I/ActivityManager(  452): Process org.schabi.newpipelegacy (pid 14925) has died.
D/ActivityManager(  452): cleanUpApplicationRecordLocked -- 14925
I/ActivityManager(  452): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.schabi.newpipelegacy/.MainActivity} from pid 623
V/Zygote  (15009): Switching descriptor 32 to /dev/null
V/Zygote  (15009): Switching descriptor 10 to /dev/null
I/ActivityManager(  452): Start proc org.schabi.newpipelegacy for activity org.schabi.newpipelegacy/.MainActivity: pid=15009 uid=10055 gids={50055, 3003, 1028, 1015}
E/dalvikvm(15009): Could not find class 'android.app.NotificationChannel', referenced from method org.schabi.newpipelegacy.App.setUpUpdateNotificationChannel
W/dalvikvm(15009): VFY: unable to resolve new-instance 50 (Landroid/app/NotificationChannel;) in Lorg/schabi/newpipelegacy/App;
D/dalvikvm(15009): VFY: replacing opcode 0x22 at 0x0015
E/dalvikvm(15009): Could not find class 'android.app.NotificationChannel', referenced from method org.schabi.newpipelegacy.App.initNotificationChannel
W/dalvikvm(15009): VFY: unable to resolve new-instance 50 (Landroid/app/NotificationChannel;) in Lorg/schabi/newpipelegacy/App;
D/dalvikvm(15009): VFY: replacing opcode 0x22 at 0x001c
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x0179 at 0x17 in Lorg/schabi/newpipelegacy/App;.setUpUpdateNotificationChannel
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x0179 at 0x1f in Lorg/schabi/newpipelegacy/App;.initNotificationChannel
I/dalvikvm(15009): Could not find method android.content.Context.getNoBackupFilesDir, referenced from method org.acra.file.Directory$6.getFile
W/dalvikvm(15009): VFY: unable to resolve virtual method 508: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
D/dalvikvm(15009): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
I/dalvikvm(15009): Could not find method org.acra.collections.ImmutableSet.iterator, referenced from method org.acra.data.StringFormat$1.toFormattedString
W/dalvikvm(15009): VFY: unable to resolve virtual method 37023: Lorg/acra/collections/ImmutableSet;.iterator ()Ljava/util/Iterator;
D/dalvikvm(15009): VFY: replacing opcode 0x6e at 0x000d
E/rsC++   (  623): RS Message thread exiting.
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
I/dalvikvm(15009): Could not find method org.acra.collections.ImmutableSet.iterator, referenced from method org.acra.data.StringFormat$2.toFormattedString
W/dalvikvm(15009): VFY: unable to resolve virtual method 37023: Lorg/acra/collections/ImmutableSet;.iterator ()Ljava/util/Iterator;
D/dalvikvm(15009): VFY: replacing opcode 0x6e at 0x000d
D/dalvikvm(15009): GC_CONCURRENT freed 231K, 8% free 3378K/3672K, paused 1ms+4ms, total 22ms
D/dalvikvm(15009): WAIT_FOR_CONCURRENT_GC blocked 3ms
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
E/dalvikvm(15009): Could not find class 'org.acra.collections.ImmutableList', referenced from method org.acra.config.CoreConfiguration.<init>
W/dalvikvm(15009): VFY: unable to resolve new-instance 5449 (Lorg/acra/collections/ImmutableList;) in Lorg/acra/config/CoreConfiguration;
D/dalvikvm(15009): VFY: replacing opcode 0x22 at 0x0015
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableSet;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
W/dalvikvm(15009): VFY: unable to find class referenced in signature (Lorg/acra/collections/ImmutableList;)
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0x1b in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0x2c in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableSet; interface 4587 'Lj$/util/Set;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableSet;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9096 at 0x37 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0x54 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0x71 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0x7c in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0x8d in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
D/dalvikvm(15009): GC_CONCURRENT freed 327K, 10% free 3522K/3912K, paused 2ms+4ms, total 21ms
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9074 at 0xb6 in Lorg/acra/config/CoreConfiguration;.<init>
I/dalvikvm(15009): Failed resolving Lorg/acra/collections/ImmutableList; interface 4581 'Lj$/util/List;'
W/dalvikvm(15009): Link of class 'Lorg/acra/collections/ImmutableList;' failed
D/dalvikvm(15009): DexOpt: unable to opt direct call 0x9073 at 0xe5 in Lorg/acra/config/CoreConfiguration;.<init>
D/AndroidRuntime(15009): Shutting down VM
W/dalvikvm(15009): threadid=1: thread exiting with uncaught exception (group=0x4193ac08)
E/AndroidRuntime(15009): FATAL EXCEPTION: main
E/AndroidRuntime(15009): Process: org.schabi.newpipelegacy, PID: 15009
E/AndroidRuntime(15009): java.lang.NoClassDefFoundError: org.acra.collections.ImmutableList
E/AndroidRuntime(15009):        at org.acra.config.CoreConfiguration.<init>(CoreConfiguration.java:118)
E/AndroidRuntime(15009):        at org.acra.config.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:835)
E/AndroidRuntime(15009):        at org.schabi.newpipelegacy.App.initACRA(App.java:210)
E/AndroidRuntime(15009):        at org.schabi.newpipelegacy.App.attachBaseContext(App.java:83)
E/AndroidRuntime(15009):        at android.app.Application.attach(Application.java:181)
E/AndroidRuntime(15009):        at android.app.Instrumentation.newApplication(Instrumentation.java:991)
E/AndroidRuntime(15009):        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/AndroidRuntime(15009):        at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
E/AndroidRuntime(15009):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
E/AndroidRuntime(15009):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime(15009):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(15009):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15009):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(15009):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(15009):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15009):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15009):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(15009):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime(15009):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  452):   Force finishing activity org.schabi.newpipelegacy/.MainActivity
I/WindowManager(  452): Screenshot max retries 4 of Token{42636aa8 ActivityRecord{41f48188 u0 org.schabi.newpipelegacy/.MainActivity t60 f}} appWin=Window{41e906a0 u0 Starting org.schabi.newpipelegacy} drawState=4
W/WindowManager(  452): Screenshot failure taking screenshot for (720x1280) to layer 21045
W/ActivityManager(  452): Activity pause timeout for ActivityRecord{41f48188 u0 org.schabi.newpipelegacy/.MainActivity t60 f}
W/GraphicBufferMapper(  623): registerBuffer(0x6039bfa0) failed -22 (Invalid argument)
E/GraphicBuffer(  623): unflatten: registerBuffer failed: Invalid argument (-22)
D/dalvikvm(  623): GC_CONCURRENT freed 2424K, 21% free 10850K/13720K, paused 2ms+17ms, total 51ms
V/RenderScript(  623): 0x608003f0 Launching thread(s), CPUs 2
E/WindowManager(  452): Starting window AppWindowToken{41f0e2c0 token=Token{42636aa8 ActivityRecord{41f48188 u0 org.schabi.newpipelegacy/.MainActivity t60}}} timed out
W/ActivityManager(  452): Activity destroy timeout for ActivityRecord{41f48188 u0 org.schabi.newpipelegacy/.MainActivity t60 f}
I/Process (15009): Sending signal. PID: 15009 SIG: 9
I/ActivityManager(  452): Process org.schabi.newpipelegacy (pid 15009) has died.
D/ActivityManager(  452): cleanUpApplicationRecordLocked -- 15009
W/InputMethodManagerService(  452): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42a599e8 attribute=null, token = android.os.BinderProxy@41df33d0
D/dalvikvm(  452): GC_CONCURRENT freed 2297K, 41% free 13525K/22576K, paused 12ms+9ms, total 72ms
D/dalvikvm(  607): GC_CONCURRENT freed 781K, 18% free 5716K/6888K, paused 3ms+2ms, total 33ms`

**Comment by drogga** [comment]
@PCMYONELOVE Does this one launch/run ?, if yes, then you should contact the owner of the fork instead, @sh000gun please enable the Issues (and maybe even Discussions) tab(s) in your repo fork, so users with issues like this one can contact you directly. Thanks.
