### ISSUE TITLE
newpipe legacy does crash when started

### ISSUE THREAD

**Issue by 470M-4n7z** [TeamNewPipe/NewPipe-legacy#87]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by conradaaron21** [comment]
I also have the same problem.

Exception
User Action: ui error
Request: App crash, UI failure
Content Country: TR
Content Language: tr
App Language: tr
Service: none
Version: 0.20.8
OS: qnx Android 4.3 - 18
Crash log
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://... flg=0x10000000 pkg=com.qnx.internal.qnxinvokeproxy }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1657)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
at android.app.Activity.startActivityForResult(Activity.java:3456)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
at android.app.Activity.startActivityForResult(Activity.java:3417)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
at android.app.Activity.startActivity(Activity.java:3653)
at android.app.Activity.startActivity(Activity.java:3621)
at org.schabi.newpipelegacy.util.ShareUtils.openUrlInBrowser(ShareUtils.java:39)
at org.schabi.newpipelegacy.report.ErrorActivity.lambda$open[Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)PolicyDialog$6(ErrorActivity.java:279)
at org.schabi.newpipelegacy.report.ErrorActivity.lambda$openPrivacyPolicyDialog$6$ErrorActivity(ErrorActivity.java)
at org.schabi.newpipelegacy.report.-$$Lambda$ErrorActivity$G4k4bXzoZQufOIGzBD8GD3omfx0.onClick(lambda)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5121)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
