### ISSUE TITLE
Unable to request any stream 

### ISSUE THREAD

**Issue by H1rkovic** [TeamNewPipe/NewPipe-legacy#90]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to search 
2. Type anything and let it load some videos 
3. Trying to start a Video is leading to a "crash" and im getting the error message as shown below

### Actual behaviour

As been described it is not possible to load any Video without getting an error that the requested website could not have been analyzed (original text in german: konnte website nicht analysieren). And I get this message since yesterday with any Video. In addition to that It's not possible for me to see the trends. NewPipe is trying to load something but I don't get any Video shown there. But that never worked on my device. I also tried to reinstall but it didn't work. 

### Expected behavior

Well I expect it to play the videos so I can listen music agaib while having the app as a background process. Thank you in advance.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=9UMxZofMNbA
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.20.8
* __OS:__ Linux samsung/d2seea/d2s:12/SP1A.210812.016/N975FXXU7GVA5:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse JSON
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.toJsonArray(YoutubeParsingHelper.java:628)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:607)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:710)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipelegacy.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:127)
	at org.schabi.newpipelegacy.util.-$$Lambda$ExtractorHelper$UQ1vNWjXRu939LDH1klSnNo2_Zg.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.grack.nanojson.JsonParserException: JSON did not contain the correct type, expected JsonArray. on line 1, char 354499
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:61)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.toJsonArray(YoutubeParsingHelper.java:626)
	... 31 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 
 - Device model:

**Comment by H1rkovic** [comment]
I don't know why and how but the issue solved itself for now.

**Comment by Sonicjhon** [comment]
I'm having the same issue I can only play it on background but sometimes it fix it if you change the video format to 3GP for some reason the comment section keep saying (no comment) but in YouTube there's a comment

**Comment by H1rkovic** [comment]
Now I'm having the issue again. I'd like to try to change the video format but I can't even start the video. It doesn't open the YouTube page of the video.
